
services:
  - type: web
    name: caficafe-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://caficafe-1.onrender.com
      - key: PRODUCTION_FRONTEND_URL
        value: https://caficafe-1.onrender.com